#!/usr/bin/env bash

if [ $# -lt 4 ]; then
    echo "bad args $@"
    exit 1
fi
podname=$1
rsip=$2
vip=$3
ldip=$4
cid=`docker ps | grep k8s_POD | grep $podname | awk '{print $1}'`
if [ "$cid" == "" ]; then
    echo "can't find container id given pod name $podname"
    exit 1
fi
pid=`docker inspect -f {{.State.Pid}} $cid`
if [ "$pid" == "" ]; then
    echo "can't get pid given pod name $podname"
    exit 1
fi
nsenter -t $pid --net /usr/local/realserver/RS_TUNL0/etc/setup_rs.sh install $rsip -i "$vip $ldip"