/*
 * Tencent is pleased to support the open source community by making TKEStack available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "tkestack.io/galaxy/pkg/ipam/apis/galaxy/v1alpha1"
)

// FakePools implements PoolInterface
type FakePools struct {
	Fake *FakeGalaxyV1alpha1
	ns   string
}

var poolsResource = schema.GroupVersionResource{Group: "galaxy.k8s.io", Version: "v1alpha1", Resource: "pools"}

var poolsKind = schema.GroupVersionKind{Group: "galaxy.k8s.io", Version: "v1alpha1", Kind: "Pool"}

// Get takes name of the pool, and returns the corresponding pool object, and an error if there is any.
func (c *FakePools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(poolsResource, c.ns, name), &v1alpha1.Pool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pool), err
}

// List takes label and field selectors, and returns the list of Pools that match those selectors.
func (c *FakePools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(poolsResource, poolsKind, c.ns, opts), &v1alpha1.PoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PoolList{ListMeta: obj.(*v1alpha1.PoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.PoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pools.
func (c *FakePools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(poolsResource, c.ns, opts))

}

// Create takes the representation of a pool and creates it.  Returns the server's representation of the pool, and an error, if there is any.
func (c *FakePools) Create(ctx context.Context, pool *v1alpha1.Pool, opts v1.CreateOptions) (result *v1alpha1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(poolsResource, c.ns, pool), &v1alpha1.Pool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pool), err
}

// Update takes the representation of a pool and updates it. Returns the server's representation of the pool, and an error, if there is any.
func (c *FakePools) Update(ctx context.Context, pool *v1alpha1.Pool, opts v1.UpdateOptions) (result *v1alpha1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(poolsResource, c.ns, pool), &v1alpha1.Pool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pool), err
}

// Delete takes name of the pool and deletes it. Returns an error if one occurs.
func (c *FakePools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(poolsResource, c.ns, name, opts), &v1alpha1.Pool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(poolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PoolList{})
	return err
}

// Patch applies the patch and returns the patched pool.
func (c *FakePools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(poolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pool), err
}
