
# kube-scheduler, --config=/etc/kubernetes/scheduler-config.yaml
# cat /etc/kubernetes/scheduler-config.yaml
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 0s
  renewDeadline: 0s
  resourceLock: ""
  resourceName: ""
  resourceNamespace: ""
  retryPeriod: 0s
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /etc/kubernetes/kube-scheduler/kubeconfig
  qps: 0
extenders:
- enableHTTPS: false
  filterVerb: filter
  bindVerb: bind
  weight: 1
  httpTimeout: 0s
  managedResources:
    - name: tke.cloud.tencent.com/eni-ip
      ignoredByScheduler: true
  nodeCacheCapable: true
  urlPrefix: http://192.168.253.174:9040/v1
