package util

import (
	"fmt"
	"strings"

	"git.code.oa.com/gaiastack/galaxy/pkg/api/galaxy/constant"
	appv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
)

// resolveDeploymentName return deployment name if pod is generated by deployment
func resolveDeploymentName(pod *corev1.Pod) string {
	if len(pod.OwnerReferences) == 1 && pod.OwnerReferences[0].Kind == "ReplicaSet" {
		// assume pod belong to deployment for convenient
		// can't parse deployment from pod name directly if deployment name is nearly 63 bytes
		// e.g. if deployment name is dp1234567890dp1234567890dp1234567890dp1234567890dp1234567890dp1 (63 bytes)
		// ReplicaSet name is dp1234567890dp1234567890dp1234567890dp1234567890dp1234567890dp1-69fd8dbc5c (74 bytes)
		// pod name is generated like dp1234567890dp1234567890dp1234567890dp1234567890dp1234567848p74
		lastIndex := strings.LastIndex(pod.OwnerReferences[0].Name, "-")
		if lastIndex == -1 {
			return ""
		}
		return pod.OwnerReferences[0].Name[:lastIndex]
	}
	return ""
}

// resolveStatefulsetName return statefulset name if pod is generated by statefulset
func resolveStatefulsetName(pod *corev1.Pod) string {
	if len(pod.OwnerReferences) == 1 && pod.OwnerReferences[0].Kind == "StatefulSet" {
		return pod.OwnerReferences[0].Name
	}
	return ""
}

type KeyObj struct {
	// stores the key format in database
	// for deployment dp_namespace_deploymentName_podName,
	// for pool pool__poolName_dp_namespace_deploymentName_podName, for statefulset sts_namespace_statefulsetName_podName
	// If deployment name is 63 bytes, e.g. dp1234567890dp1234567890dp1234567890dp1234567890dp1234567890dp1
	// deployment pod name will be 63 bytes with modified suffix, e.g. dp1234567890dp1234567890dp1234567890dp1234567890dp1234567848p74
	// So we can't get deployment name from pod name and have to store deployment name with pod name
	KeyInDB      string
	IsDeployment bool
	AppName      string
	PodName      string
	Namespace    string
	// the annotation value if pod has pool annotation
	PoolName string
}

func NewKeyObj(isDeployment bool, namespace, appName, podName, poolName string) *KeyObj {
	k := &KeyObj{IsDeployment: isDeployment, AppName: appName, PodName: podName, Namespace: namespace, PoolName: poolName}
	k.genKey()
	return k
}

func (k *KeyObj) genKey() {
	var prefix string
	if k.PoolName != "" {
		prefix = fmt.Sprintf("%s%s_", poolPrefix, k.PoolName)
		if k.AppName == "" {
			k.KeyInDB = prefix
			return
		}
	}
	appTypePrefix := statefulsetPrefixKey
	if k.IsDeployment {
		appTypePrefix = deploymentPrefixKey
	}
	if k.PoolName == "" && k.AppName == "" && k.Namespace == "" {
		k.KeyInDB = ""
		return
	}
	k.KeyInDB = fmt.Sprintf("%s%s%s_%s_%s", prefix, appTypePrefix, k.Namespace, k.AppName, k.PodName)
}

// PoolPrefix returns the common key prefix in database, for deployment dp_namespace_deploymentName_
// for pool pool__poolName_, for statefulset sts_namespace_statefulsetName_
// For now, if it is a statefulset pod, PoolPrefix is useless since we reserve ip by full pod name
// PoolPrefix is used by pool and deployment only.
func (k *KeyObj) PoolPrefix() string {
	if k.PoolName != "" {
		return fmt.Sprintf("%s%s_", poolPrefix, k.PoolName)
	}
	if k.IsDeployment {
		return fmt.Sprintf("%s%s_%s_", deploymentPrefixKey, k.Namespace, k.AppName)
	}
	return fmt.Sprintf("%s%s_%s_", statefulsetPrefixKey, k.Namespace, k.AppName)
}

func (k *KeyObj) PoolAppPrefix() string {
	if k.PoolName != "" {
		appTypePrefix := statefulsetPrefixKey
		if k.IsDeployment {
			appTypePrefix = deploymentPrefixKey
		}
		return fmt.Sprintf("%s%s_%s%s_%s_", poolPrefix, k.PoolName, appTypePrefix, k.Namespace, k.AppName)
	}
	return k.PoolPrefix()
}

const (
	// ip pool may be shared with other namespaces, so leave namespace empty
	poolPrefix           = "pool__"
	deploymentPrefixKey  = "dp_"
	statefulsetPrefixKey = "sts_"
)

func FormatKey(pod *corev1.Pod) *KeyObj {
	pool := constant.GetPool(pod.Annotations)
	deploymentName := resolveDeploymentName(pod)
	keyObj := &KeyObj{
		PoolName:  pool,
		PodName:   pod.Name,
		Namespace: pod.Namespace}
	if deploymentName != "" {
		keyObj.AppName = deploymentName
		keyObj.IsDeployment = true
	} else {
		stsName := resolveStatefulsetName(pod)
		if stsName == "" {
			return keyObj
		}
		keyObj.AppName = stsName
	}
	keyObj.genKey()
	return keyObj
}

func ParseKey(key string) *KeyObj {
	keyObj := &KeyObj{KeyInDB: key}
	removedPoolKey := key
	if strings.HasPrefix(key, poolPrefix) {
		// _ippool__poolName_deployment_namespace_deploymentName_podName
		parts := strings.SplitN(key[len(poolPrefix):], "_", 2) // poolName and deployment_namespace_deploymentName_podName
		if len(parts) != 2 {
			return keyObj
		}
		keyObj.PoolName = parts[0]
		if strings.HasPrefix(parts[1], deploymentPrefixKey[1:]) {
			removedPoolKey = "_" + parts[1]
		} else {
			removedPoolKey = parts[1]
		}
	}
	if strings.HasPrefix(removedPoolKey, deploymentPrefixKey) {
		keyObj.IsDeployment = true
		keyObj.AppName, keyObj.PodName, keyObj.Namespace = ResolveDpKey(removedPoolKey)
	} else {
		keyObj.AppName, keyObj.PodName, keyObj.Namespace = resolveStsKey(removedPoolKey)
	}
	return keyObj
}

// resolveStatefulSetKey returns appname, podName, namespace
// "sts_kube-system_fip-bj_fip-bj-111": {"fip-bj", "fip-bj-111", "kube-system"}
func resolveStsKey(key string) (string, string, string) {
	if strings.HasPrefix(key, statefulsetPrefixKey) {
		// _ is not a valid char in appname
		parts := strings.Split(key, "_")
		if len(parts) == 4 {
			return parts[2], parts[3], parts[1]
		}
	}
	return "", "", ""
}

// ResolveDpKey returns appname, podname, namespace
// "dp_default_dp1_dp1-rs1-pod1": {"dp1", "dp1-rs1-pod1", "default"}
func ResolveDpKey(key string) (string, string, string) {
	if IsDeploymentKey(key) {
		parts := strings.Split(key, "_")
		if len(parts) == 4 {
			return parts[2], parts[3], parts[1]
		}
	}
	return "", "", ""
}

func IsDeploymentKey(key string) bool {
	return strings.HasPrefix(key, deploymentPrefixKey)
}

func IsIPPoolKey(key string) bool {
	return strings.HasPrefix(key, "pool__")
}

func Join(name, namespace string) string {
	return fmt.Sprintf("%s_%s", namespace, name)
}

func PodName(pod *corev1.Pod) string {
	return fmt.Sprintf("%s_%s", pod.Namespace, pod.Name)
}

func StatefulsetName(ss *appv1.StatefulSet) string {
	return fmt.Sprintf("%s_%s", ss.Namespace, ss.Name)
}

func DeploymentName(dp *appv1.Deployment) string {
	return fmt.Sprintf("%s_%s", dp.Namespace, dp.Name)
}
